### ISSUE TITLE
v0.2.4 - broken build

### ISSUE THREAD

**Issue by jbaginski** [mrmike/Ok2Curl#20]
after upgrading from v0.2.3 to v0.2.4

```
...
:app:transformClassesWithDexForLiveDebug
Dex: Error converting bytecode to dex:
Cause: Dex cannot parse version 52 byte code.
This is caused by library dependencies that have been compiled using Java 8 or above.
If you are using the 'java' gradle plugin in a library submodule add
targetCompatibility = '1.7'
sourceCompatibility = '1.7'
to that submodule's build.gradle file.
    UNEXPECTED TOP-LEVEL EXCEPTION:
    java.lang.RuntimeException: Exception parsing classes
    	at com.android.dx.command.dexer.Main.processClass(Main.java:761)
    	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:727)
    	at com.android.dx.command.dexer.Main.access$1200(Main.java:87)
    	at com.android.dx.command.dexer.Main$FileBytesConsumer.processFileBytes(Main.java:1655)
    	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
    	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
    	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
    	at com.android.dx.command.dexer.Main.processOne(Main.java:681)
    	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:578)
    	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:315)
    	at com.android.dx.command.dexer.Main.run(Main.java:286)
    	at com.android.builder.internal.compiler.DexWrapper.run(DexWrapper.java:52)
    	at com.android.builder.core.AndroidBuilder$2.call(AndroidBuilder.java:1511)
    	at com.android.builder.core.AndroidBuilder$2.call(AndroidBuilder.java:1507)
    	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    	at java.lang.Thread.run(Thread.java:745)
    Caused by: com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)
    	at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:472)
    	at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)
    	at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)
    	at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)
    	at com.android.dx.command.dexer.Main.parseClass(Main.java:773)
    	at com.android.dx.command.dexer.Main.access$1600(Main.java:87)
    	at com.android.dx.command.dexer.Main$ClassParserTask.call(Main.java:1694)
    	at com.android.dx.command.dexer.Main.processClass(Main.java:758)
    	... 17 more

1 error; aborting
:app:transformClassesWithDexForLiveDebug FAILED
```

I have only one module (android application)
```
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_7
        targetCompatibility JavaVersion.VERSION_1_7
    }
```

**Comment by mrmike** [comment]
I'll fix it, for now you can use `0.2.3`

Thanks for reporting issue.

**Comment by mrmike** [comment]
Should be fixed in latest version https://github.com/mrmike/Ok2Curl/releases/tag/0.2.5

**Comment by jbaginski** [comment]
thanks @mrmike 👍
